#
# A GitHub workflow to build containers for each semantically versioned tag (i.e. vX.Y.Z).
#
# help:
# - tagging info: https://github.com/docker/build-push-action/blob/v2/docs/advanced/tags-labels.md
# - original gist: https://gist.github.com/robb-j/049217ca8cecf4e214b8b82123f7371b
#

name: "Build Container"

on:
  push:
    tags: [v*.*.*]

jobs:
  build_server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/robb-j/sator
          tags: |
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
